# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [
      <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot =
  {
    loader =
    {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      
      grub =
      {
        enable = true;
        version = 2;
        efiSupport = true;
        devices = [ "nodev" ];
      };
    };
    
    initrd = 
    {
      availableKernelModules = 
      [
        "ehci_pci" 
        "ahci"
        "xhci_pci"
        "usb_storage"
        "sd_mod"
        "sr_mod"
        "sdhci_pci"
      ];
      
      # https://bugzilla.kernel.org/show_bug.cgi?id=110941
      #kernelParams = [ "intel_pstate=no_hwp" ];
      
      kernelModules = 
      [
        "usb_storage"
        "dm_snapshot"
        "fbcon"
        "kvm-intel"
        "tp_smapi"
      ];
      
      luks =
      {
        mitigateDMAAttacks = true;
        
        devices =
        [
          {
            name = "root";
            preLVM = true;
            #device = "/dev/sda2";
            device = "/dev/disk/by-uuid/bd46d9d9-8384-4672-b782-fd133004cad0";
            #allowDiscards = true;
          };
          
          # cryptsetup default settings?
          #cryptoModules =
          #{
          #	[
          #		"aes"
          #		"xts"
          #		"sha256"
          #	];
          #};
        ];
      };
    };
    
    extraModulePackages =
    [
      config.boot.kernelPackages.tp_smapi
    ];
  };


  fileSystems."/" =
    { 
      device = "/dev/disk/by-uuid/bd46d9d9-8384-4672-b782-fd133004cad0";
      fsType = "f2fs";
    };

  fileSystems."/boot" =
    { 
      device = "/dev/disk/by-uuid/2643-DA52";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
